name: Backend

on: [push]

jobs:
  install:
    uses: friggframework/ci-workflow-steps/.github/workflows/ci-step.yml@main
    with:
      cache-key-prefix: hubspot-crm-backend
      step: none
      working-directory: hubspot-crm/backend

  lint:
    uses: friggframework/ci-workflow-steps/.github/workflows/ci-step.yml@main
    needs: [install]
    with:
      cache-key-prefix: hubspot-crm-backend
      step: lint
      working-directory: hubspot-crm/backend

  test:
    uses: friggframework/ci-workflow-steps/.github/workflows/ci-step.yml@main
    needs: [install]
    with:
      cache-key-prefix: hubspot-crm-backend
      step: test
      working-directory: hubspot-crm/backend
