name: Frontend

on: [push]

jobs:
  install:
    uses: lefthookhq/ci-workflow-steps/.github/workflows/ci-step.yml@main
    with:
      cache-key-prefix: hubspot-crm-frontend
      install-directory: ./
      step: none
      working-directory: hubspot-crm/frontend

  lint:
    uses: lefthookhq/ci-workflow-steps/.github/workflows/ci-step.yml@main
    needs: [install]
    with:
      cache-key-prefix: hubspot-crm-frontend
      install-directory: ./
      step: lint
      working-directory: hubspot-crm/frontend

  test:
    uses: lefthookhq/ci-workflow-steps/.github/workflows/ci-step.yml@main
    needs: [install]
    with:
      cache-key-prefix: hubspot-crm-frontend
      install-directory: ./
      step: test
      working-directory: hubspot-crm-frontend
